# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(help_text='文档', max_length=35, upload_to='text/%Y/%m/%d', verbose_name='文档')),
                ('text_type', models.CharField(choices=[('plant', '种植'), ('aquaculture', '水产养殖'), ('agri_industry', '农资业'), ('agri_and_sideline_industries', '农副加工业'), ('animal', '畜牧业')], help_text='文档类型', max_length=50, verbose_name='文档类型')),
                ('download_nums', models.IntegerField(default=0, help_text='下载量', verbose_name='下载量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='文档添加时间', verbose_name='文档添加时间')),
            ],
            options={
                'verbose_name': '文件上传表',
                'verbose_name_plural': '文件上传表',
            },
        ),
    ]
