# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='user',
            field=models.ForeignKey(default=None, help_text='上传用户', on_delete=django.db.models.deletion.CASCADE, related_name='text_of_user', to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
        ),
    ]
