# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_textmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='file_type',
            field=models.CharField(choices=[('docx', 'word文档'), ('pptx', 'ppt文档'), ('xlsx', 'excel文档'), ('pdf', 'pdf文档')], default='docx', help_text='上传文件的格式', max_length=10, verbose_name='上传文件的格式'),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_type',
            field=models.CharField(choices=[('plant', '种植'), ('aquaculture', '水产养殖'), ('agri_industry', '农资业'), ('agri_and_sideline_industries', '农副加工业'), ('animal', '畜牧业')], default='plant', help_text='文档类型', max_length=50, verbose_name='文档类型'),
        ),
    ]
