# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180414_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='file_size',
            field=models.IntegerField(default=0, help_text='文件大小统计', verbose_name='文件大小统计'),
        ),
    ]
