# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_textmodel_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='pdf_path',
            field=models.CharField(default='', help_text='pdf_地址', max_length=120, verbose_name='pdf_地址'),
        ),
    ]
