# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20180418_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='text',
            field=models.FileField(help_text='文档', max_length=79, upload_to='text/%Y/%m/%d', verbose_name='文档'),
        ),
    ]
