# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20180420_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='file_name',
            field=models.CharField(default='', help_text='文件名', max_length=59, verbose_name='文件名'),
        ),
    ]
