# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='父级评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_com', to='operation.VideoComment', verbose_name='父级评论'),
        ),
    ]
