# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180412_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='is_love',
            field=models.BooleanField(default=False, help_text='用户是否点赞过', verbose_name='用户是否点赞过'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='point_love_nums',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
    ]
