# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180412_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomment',
            name='is_love',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='point_love_nums',
        ),
    ]
