# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 20:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20180412_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPointLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_love', models.BooleanField(default=False, verbose_name='是否赞过')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('user', models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_point', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='videocomment',
            name='point_love_nums',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='userpointlove',
            name='video_comment',
            field=models.OneToOneField(help_text='评论', on_delete=django.db.models.deletion.CASCADE, related_name='video_com', to='operation.VideoComment', verbose_name='评论'),
        ),
    ]
