# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180412_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpointlove',
            name='is_love',
        ),
    ]
