# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_remove_userpointlove_is_love'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='用户点赞文本', max_length=41, verbose_name='用户点赞文本')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('video', models.ForeignKey(help_text='评论', on_delete=django.db.models.deletion.CASCADE, to='operation.VideoComment', verbose_name='评论')),
            ],
        ),
    ]
