# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20180412_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlove',
            name='file_path',
            field=models.CharField(default='', help_text='用户点赞文本', max_length=41, verbose_name='用户点赞文本'),
        ),
    ]
