# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20180412_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlove',
            name='video',
        ),
        migrations.AlterField(
            model_name='userpointlove',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_point', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='CommentLove',
        ),
    ]
