# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20180412_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpointlove',
            options={'verbose_name': '用户点赞', 'verbose_name_plural': '用户点赞'},
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_love',
            field=models.BooleanField(default=False, help_text='是否点过赞', verbose_name='是否点过赞'),
        ),
    ]
