# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20180413_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointlove',
            name='video_comment',
            field=models.ForeignKey(help_text='评论id', on_delete=django.db.models.deletion.CASCADE, related_name='video_com', to='operation.VideoComment', verbose_name='评论'),
        ),
    ]
