# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 21:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20180413_1533'),
        ('operation', '0013_auto_20180413_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('user', models.ForeignKey(help_text='收藏用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
                ('video', models.ForeignKey(help_text='收藏视频', on_delete=django.db.models.deletion.CASCADE, related_name='file_video', to='courses.FileVideoModel', verbose_name='收藏的视屏')),
            ],
            options={
                'verbose_name': '视频收藏',
                'verbose_name_plural': '视频收藏',
            },
        ),
    ]
