# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_textmodel_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0014_userfavvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('text', models.ForeignKey(help_text='上传文档', on_delete=django.db.models.deletion.CASCADE, to='resources.TextModel', verbose_name='上传文档')),
                ('user', models.ForeignKey(help_text='上传用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '用户上传文档',
                'verbose_name_plural': '用户上传文档',
            },
        ),
    ]
