# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 10:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20180413_1533'),
        ('operation', '0016_auto_20180420_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField(help_text='回复目标id', verbose_name='回复目标id')),
                ('to_uid', models.IntegerField(help_text='目标用户id', verbose_name='目标用户id')),
                ('reply_type', models.IntegerField(choices=[(1, '回复评论的回复'), (2, '回复的回复')], help_text='回复类型', verbose_name='回复类型')),
                ('comment', models.CharField(help_text='评论内容', max_length=150, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '二级回复表',
                'verbose_name_plural': '二级回复表',
            },
        ),
        migrations.CreateModel(
            name='TestVideoCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='评论内容', max_length=150, verbose_name='评论内容')),
                ('point_love_nums', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('is_love', models.BooleanField(default=False, help_text='是否点过赞', verbose_name='是否点过赞')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('user', models.ForeignKey(help_text='评论用户', on_delete=django.db.models.deletion.CASCADE, related_name='test_video_user_comment', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
                ('video', models.ForeignKey(help_text='所评论的视频', on_delete=django.db.models.deletion.CASCADE, related_name='test_video_file_comment', to='courses.FileVideoModel', verbose_name='所评论的视频')),
            ],
            options={
                'verbose_name': '二级评论表',
                'verbose_name_plural': '二级评论表',
            },
        ),
        migrations.AddField(
            model_name='testreplymodel',
            name='comment_id',
            field=models.ForeignKey(help_text='根评论', on_delete=django.db.models.deletion.CASCADE, related_name='child_com', to='operation.TestVideoCommentModel', verbose_name='根评论'),
        ),
        migrations.AddField(
            model_name='testreplymodel',
            name='from_uid',
            field=models.ForeignKey(help_text='回复用户', on_delete=django.db.models.deletion.CASCADE, related_name='from_uid', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
    ]
