# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_auto_20180427_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreplymodel',
            name='from_uid',
            field=models.IntegerField(help_text='回复用户', verbose_name='回复用户'),
        ),
    ]
