# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_auto_20180427_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreplymodel',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
