# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_auto_20180427_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreplymodel',
            name='reply_type',
            field=models.IntegerField(choices=[(1, '回复评论的回复'), (2, '回复的回复')], default=1, help_text='回复类型', verbose_name='回复类型'),
        ),
    ]
