# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_auto_20180427_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreplymodel',
            name='to_uid',
            field=models.CharField(help_text='目标用户id', max_length=10, verbose_name='目标用户id'),
        ),
    ]
