# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_auto_20180427_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreplymodel',
            name='from_uid',
            field=models.ForeignKey(help_text='回复用户', on_delete=django.db.models.deletion.CASCADE, related_name='test_reply_user_from_uid', to=settings.AUTH_USER_MODEL, verbose_name='回复用户'),
        ),
        migrations.AlterField(
            model_name='testreplymodel',
            name='to_uid',
            field=models.ForeignKey(help_text='目标用户id', on_delete=django.db.models.deletion.CASCADE, related_name='test_reply_user_to_uid', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id'),
        ),
    ]
