# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_auto_20180427_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreplymodel',
            name='comment_id',
            field=models.ForeignKey(help_text='根评论', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_com', to='operation.TestVideoCommentModel', verbose_name='根评论'),
        ),
    ]
