# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_auto_20180427_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointlove',
            name='video_comment',
            field=models.IntegerField(help_text='评论id', verbose_name='评论'),
        ),
    ]
