# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_auto_20180427_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointlove',
            name='reply_type',
            field=models.IntegerField(choices=[(1, '回复评论的回复'), (2, '回复的回复')], help_text='点赞类型', verbose_name='点赞类型'),
        ),
    ]
