# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0033_auto_20180427_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpointlove',
            name='video_comment_parent',
            field=models.IntegerField(default=1, help_text='主评论id', verbose_name='主评论'),
        ),
    ]
