# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0008_auto_20180517_1615'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0035_remove_userpointlove_video_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavMession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('task', models.ForeignKey(help_text='收藏问答', on_delete=django.db.models.deletion.CASCADE, to='mession_square.TaskModel', verbose_name='收藏问答')),
                ('user', models.ForeignKey(help_text='收藏用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '问答收藏',
                'verbose_name_plural': '问答收藏',
            },
        ),
    ]
