# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(help_text='视频名称', max_length=11, verbose_name='视频名称')),
                ('desc', models.CharField(help_text='视频描述', max_length=41, verbose_name='视频描述')),
                ('video_img', models.ImageField(default='video_img/default.png', help_text='视频封面', upload_to='video_img/%Y/%m/%d', verbose_name='视频封面')),
                ('click_num', models.IntegerField(default=0, help_text='视频点击量', verbose_name='视频点击量')),
                ('fav_num', models.IntegerField(default=0, help_text='视频收藏量', verbose_name='视频收藏量')),
                ('video_kind', models.CharField(choices=[('plant', '种植'), ('aquaculture', '水产养殖'), ('agri_industry', '农资业'), ('agri_and_sideline_industries', '农副加工业'), ('animal', '畜牧业')], default='plant', help_text='视频类别', max_length=31, verbose_name='视频类别')),
                ('url', models.CharField(default='', help_text='访问地址', max_length=200, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='视频添加时间', verbose_name='视频添加时间')),
                ('user', models.ForeignKey(help_text='上传视频用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_p_info', to=settings.AUTH_USER_MODEL, verbose_name='上传视频用户')),
            ],
            options={
                'verbose_name': '视频资源',
                'verbose_name_plural': '视频资源',
            },
        ),
        migrations.RemoveField(
            model_name='filevideo',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileVideo',
        ),
    ]
