# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180411_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filevideomodel',
            name='user',
            field=models.ForeignKey(help_text='上传视频用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_ptoi', to=settings.AUTH_USER_MODEL, verbose_name='上传视频用户'),
        ),
    ]
