# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180411_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filevideomodel',
            name='desc',
            field=models.CharField(default='视频很好看，快来看吧!', help_text='视频描述', max_length=41, verbose_name='视频描述'),
        ),
        migrations.AlterField(
            model_name='filevideomodel',
            name='url',
            field=models.CharField(help_text='访问地址', max_length=200, verbose_name='访问地址'),
        ),
    ]
