# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180413_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevideomodel',
            name='video_file',
            field=models.FileField(default='', help_text='视频', upload_to='video/%Y/%m', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='filevideomodel',
            name='url',
            field=models.CharField(default='', help_text='访问地址', max_length=200, verbose_name='访问地址'),
        ),
    ]
