# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_filevideomodel_qi_niu_video_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filevideomodel',
            name='qi_niu_video_img',
        ),
        migrations.AlterField(
            model_name='filevideomodel',
            name='video_img',
            field=models.CharField(default='', help_text='七牛云视频封面', max_length=81, verbose_name='七牛云视频封面'),
        ),
    ]
