# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180601_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filevideomodel',
            name='video_img',
            field=models.CharField(default='http://p71yd5lgg.bkt.clouddn.com/default.png', help_text='七牛云视频封面', max_length=81, verbose_name='七牛云视频封面'),
        ),
    ]
