# -*- coding:utf-8 _*-
__author__ = 'luyue'
__date__ = '2018/4/14 23:47'

# import sys, os, pythoncom
# import comtypes.client
# from win32com.client import Dispatch, constants, gencache
#
#
# def doc2pdf(input, output):
#     pythoncom.CoInitialize()
#     GenerateSupport()
#     w = Dispatch("Word.Application")
#
#     try:
#         doc = w.Documents.Open(input, ReadOnly=1)
#         doc.ExportAsFixedFormat(output, constants.wdExportFormatPDF,
#                                 Item=constants.wdExportDocumentWithMarkup,
#                                 CreateBookmarks=constants.wdExportCreateHeadingBookmarks)
#         return 0
#     except:
#         return 1
#     finally:
#         w.Quit(constants.wdDoNotSaveChanges)
#
# def pptx2pdf(input, output, formatType = 32):
#     pythoncom.CoInitialize()
#     powerpoint = comtypes.client.CreateObject('Powerpoint.Application')
#     powerpoint.Visible = 1
#     deck = powerpoint.Presentations.Open(input)
#     deck.SaveAs(output, formatType)
#     deck.Close()
#     powerpoint.Quit()
#     return 1
#
# def execl2pdf(input, output):
#     pythoncom.CoInitialize()
#     o = Dispatch("Excel.Application")
#     o.Visible = False
#     wb = o.Workbooks.Open(input)
#     wb.ActiveSheet.ExportAsFixedFormat(0, output)
#     wb.Close(SaveChanges=0)
#     return 1
#
# def GenerateSupport():
#     # enable python COM support for Word 2007
#     # this is generated by: makepy.py -i "Microsoft Word 12.0 Object Library"
#     gencache.EnsureModule('{00020905-0000-0000-C000-000000000046}', 0, 8, 4)
#
# if __name__ == '__main__':
#     # GenerateSupport()
#     # doc2pdf(r'D:\Agricultural_Culture\Agri\media\text\2018\04\14\实训4_1.docx', r'D:\Agricultural_Culture\Agri\media\text\2018\04\14\实训4_1.pdf')
#     # execl2pdf(r'D:\Agricultural_Culture\Agri\apps\utils\test_file\file.xlsx', r'D:\Agricultural_Culture\Agri\apps\utils\test_file\file.pdf')
#     pptx2pdf(input=r'D:\Agricultural_Culture\Agri\apps\utils\test_file\test_ppt.pptx', output=r'D:\Agricultural_Culture\Agri\apps\utils\test_file\test_ppt.pdf')
