# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180410_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='code_type',
            field=models.CharField(choices=[('register', '注册'), ('reset_password', '忘记密码')], default='register', help_text='验证码类型', max_length=11, verbose_name='验证码类型'),
        ),
    ]
