# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verifycode_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='code_type',
        ),
    ]
