# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verifycode_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='code_type',
            field=models.CharField(choices=[('register', '注册'), ('reset_password', '忘记密码')], default='register', help_text='验证码类型', max_length=15, verbose_name='验证码类型'),
        ),
    ]
