# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180410_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_del',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_del',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
    ]
