# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180411_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='手机号码(不填，后台处理)', max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
