# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180413_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qi_niu_image',
            field=models.CharField(default='', help_text='七牛云上传图片地址', max_length=81, verbose_name='七牛云上传图片地址'),
        ),
    ]
