# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinfo_qi_niu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='qi_niu_image',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.CharField(default='', help_text='七牛云上传图片地址', max_length=81, verbose_name='七牛云上传图片地址'),
        ),
    ]
