# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 16:17
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='提问标题', max_length=25, verbose_name='提问标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', help_text='任务描述', verbose_name='任务描述')),
                ('mession_kind', models.CharField(help_text='问题分类', max_length=8, verbose_name='问题分类')),
                ('point_nums', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('attention_nums', models.IntegerField(default=0, help_text='关注数', verbose_name='关注数')),
                ('task_level', models.IntegerField(choices=[(1, '游客级别'), (2, '普通用户界别'), (3, '教师级别')], default=1, help_text='问题级别', verbose_name='问题级别')),
                ('add_times', models.DateField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('user', models.ForeignKey(help_text='提问用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提问用户')),
            ],
            options={
                'verbose_name': '提问表',
                'verbose_name_plural': '提问表',
            },
        ),
    ]
