# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mession_square', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='回答用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_reply_user', to=settings.AUTH_USER_MODEL, verbose_name='回答用户')),
            ],
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(help_text='提问用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL, verbose_name='提问用户'),
        ),
    ]
