# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0003_auto_20180516_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='content',
            field=models.TextField(help_text='问题内容', verbose_name='问题内容'),
        ),
    ]
