# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0005_taskreplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='reply_nums',
            field=models.IntegerField(default=0, help_text='回答数', verbose_name='回答数'),
        ),
    ]
