# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0006_taskmodel_reply_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='test_task/task/', verbose_name='图片')),
            ],
        ),
    ]
