# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 14:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mession_square', '0008_auto_20180517_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttentionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_times', models.DateField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('task', models.ForeignKey(help_text='关注问题', on_delete=django.db.models.deletion.CASCADE, to='mession_square.TaskModel', verbose_name='关注问题')),
                ('user', models.ForeignKey(help_text='关注用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关注用户')),
            ],
            options={
                'verbose_name': '关注表',
                'verbose_name_plural': '关注表',
            },
        ),
        migrations.AlterModelOptions(
            name='taskreplymodel',
            options={'verbose_name': '回答表', 'verbose_name_plural': '回答表'},
        ),
        migrations.AddField(
            model_name='taskreplymodel',
            name='comment_nums',
            field=models.IntegerField(default=0, help_text='评论数', verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='taskreplymodel',
            name='point_nums',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
    ]
