# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 16:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mession_square', '0010_remove_taskmodel_point_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='评论内容', max_length=150, verbose_name='评论内容')),
                ('point_love_nums', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('is_love', models.BooleanField(default=False, help_text='是否点过赞', verbose_name='是否点过赞')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '二级评论表',
                'verbose_name_plural': '二级评论表',
            },
        ),
        migrations.CreateModel(
            name='TaskReplyCommentReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.IntegerField(help_text='回复目标id', verbose_name='回复目标id')),
                ('reply_type', models.IntegerField(choices=[(1, '回复评论的回复'), (2, '回复的回复')], default=1, help_text='回复类型', verbose_name='回复类型')),
                ('comment', models.CharField(help_text='评论内容', max_length=150, verbose_name='评论内容')),
                ('point_love_nums', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('is_love', models.BooleanField(default=False, help_text='是否点过赞', verbose_name='是否点过赞')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('comment_id', models.ForeignKey(help_text='根评论', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mession_square.TaskReplyComment', verbose_name='根评论')),
                ('from_uid', models.ForeignKey(help_text='回复用户', on_delete=django.db.models.deletion.CASCADE, related_name='task_reply_from_uid', to=settings.AUTH_USER_MODEL, verbose_name='回复用户')),
                ('to_uid', models.ForeignKey(help_text='目标用户id', on_delete=django.db.models.deletion.CASCADE, related_name='task_reply_to_uid', to=settings.AUTH_USER_MODEL, verbose_name='目标用户id')),
            ],
            options={
                'verbose_name': '二级回复表',
                'verbose_name_plural': '二级回复表',
            },
        ),
        migrations.CreateModel(
            name='TaskReplyPointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_times', models.DateField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='taskreplymodel',
            name='is_love',
            field=models.BooleanField(default=False, help_text='是否点赞', verbose_name='是否点赞'),
        ),
        migrations.AddField(
            model_name='taskreplypointmodel',
            name='task_reply',
            field=models.ForeignKey(help_text='回答', on_delete=django.db.models.deletion.CASCADE, to='mession_square.TaskReplyModel', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='taskreplypointmodel',
            name='user',
            field=models.ForeignKey(help_text='点赞用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='taskreplycomment',
            name='task_reply',
            field=models.ForeignKey(help_text='所评论的回答', on_delete=django.db.models.deletion.CASCADE, to='mession_square.TaskReplyModel', verbose_name='所评论的回答'),
        ),
        migrations.AddField(
            model_name='taskreplycomment',
            name='user',
            field=models.ForeignKey(help_text='评论用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
    ]
