# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0011_auto_20180521_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='mession_kind',
            field=models.CharField(help_text='问题分类', max_length=36, verbose_name='问题分类'),
        ),
    ]
