# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mession_square', '0012_auto_20180521_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.IntegerField(help_text='目标id', verbose_name='目标id')),
                ('to_id_type', models.IntegerField(choices=[(1, '点赞回答'), (2, '点赞根评论'), (3, '点赞子评论')], help_text='点赞类型:1(点赞回答)，2(点赞根评论)，3(点赞子评论)', verbose_name='点赞类型')),
                ('add_times', models.DateField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('user', models.ForeignKey(help_text='点赞用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '点赞表',
                'verbose_name_plural': '点赞表',
            },
        ),
        migrations.DeleteModel(
            name='TestTaskModel',
        ),
    ]
