# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0013_auto_20180523_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskreplycomment',
            old_name='point_love_nums',
            new_name='point_nums',
        ),
        migrations.RenameField(
            model_name='taskreplycommentreplymodel',
            old_name='point_love_nums',
            new_name='point_nums',
        ),
    ]
