# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0014_auto_20180523_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpointmodel',
            name='to_id',
            field=models.IntegerField(default=1, help_text='目标id', verbose_name='目标id'),
        ),
        migrations.AlterField(
            model_name='taskpointmodel',
            name='to_id_type',
            field=models.IntegerField(choices=[(1, '点赞回答'), (2, '点赞根评论'), (3, '点赞子评论')], default=1, help_text='点赞类型:1(点赞回答)，2(点赞根评论)，3(点赞子评论)', verbose_name='点赞类型'),
        ),
    ]
