# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0015_auto_20180523_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreplypointmodel',
            name='task_reply',
        ),
        migrations.RemoveField(
            model_name='taskreplypointmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='taskpointmodel',
            name='user',
            field=models.ForeignKey(help_text='点赞_用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞_用户'),
        ),
        migrations.DeleteModel(
            name='TaskReplyPointModel',
        ),
    ]
