# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0016_auto_20180523_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreplycomment',
            name='comment_nums',
            field=models.IntegerField(default=0, help_text='评论数', verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='taskreplycommentreplymodel',
            name='reply_type',
            field=models.IntegerField(choices=[(1, '回复主评论的回复'), (2, '回复的回复')], default=1, help_text="(1, '回复主评论的回复'),(2, '回复子评论的回复'),", verbose_name='回复类型'),
        ),
    ]
