# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mession_square', '0017_auto_20180523_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattentiontask',
            name='task',
            field=models.ForeignKey(help_text='关注的问题', on_delete=django.db.models.deletion.CASCADE, to='mession_square.TaskModel', verbose_name='关注问题'),
        ),
    ]
