# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 09:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mession_square', '0018_auto_20180601_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='回复内容', max_length=199, verbose_name='回复内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='留言时间')),
                ('receive_user', models.ForeignKey(help_text='接收人id', on_delete=django.db.models.deletion.CASCADE, related_name='L_M_receive_user', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('send_user', models.ForeignKey(help_text='发送人id', on_delete=django.db.models.deletion.CASCADE, related_name='L_M_send_user', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
            },
        ),
        migrations.CreateModel(
            name='LeaveMessageReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='回复内容', max_length=199, verbose_name='回复内容')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('leaveM', models.ForeignKey(help_text='留言表id', on_delete=django.db.models.deletion.CASCADE, to='mession_square.LeaveMessageModel', verbose_name='留言表')),
                ('user', models.ForeignKey(help_text='回复人id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
            ],
        ),
    ]
