"""
Django settings for Agricultural project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'expr_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ze%(m8s!et-*ti-$8s%a(4zwvegu(=%0pif4xb41b@zr#-wf#l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition
AUTH_USER_MODEL = 'users.UserProfile'
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
    'social_core.backends.weibo.WeiboOAuth2',
    'social_core.backends.qq.QQOAuth2',
    'social_core.backends.weixin.WeixinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'courses.apps.CoursesConfig',
    'operation.apps.OperationConfig',
    'resources.apps.ResourcesConfig',
    'mession_square.apps.MessionSquareConfig',
    'xadmin',
    'DjangoUeditor',
    'crispy_forms',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'social_django',
]

MIDDLEWARE_CLASSES = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Agri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #第三方登录
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'Agri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'agri_test',
        'USER': 'root',
        'PASSWORD': 'wxhxx520',
        'HOST': '127.0.0.1',
        #设置数据库引擎(mysql5.7之后设置默认引擎的语句发生改变(原来：set storage_engine=INNODE)
        'OPTIONS': { 'init_command': 'SET default_storage_engine=INNODB;' },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

#设置时区
LANGUAGE_CODE = 'zh-hans'  #中文支持，django1.8以后支持；1.8以前是zh-cn
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False   #默认是Ture，时间是utc时间，由于我们要用本地时间，所用手动修改为false！！！！


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#REST_FRAMEWORK相关配置
REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'EXCEPTION_HANDLER': 'apps.utils.custom_exception_handler.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

#解决跨域请求
CORS_ORIGIN_ALLOW_ALL = True

#云片网api_key
API_KEY = '3b1409b3c9c30bd557d91f9c2e00263b'
YUN_PIAN_URL = 'https://sms.yunpian.com/v2/sms/single_send.json'

#七牛云相关设置
AccessKey = 'ueydTjsLS3akQ5jTgZXNsWo8y7CPygsFPpT9fuZ3'
SecretKey = '0cSK9vOl-s6cf16qRh_vP1ffiILPL2gRMWfgTzWG'
Bucket_Name = 'agriculture-first'
WL = 'http://p71yd5lgg.bkt.clouddn.com/'

#手机号码正则表达式
REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"

#JWT的一些设置
import datetime
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

#自定义一些相关全局变量
VIDEO_POINT_LOVE_PATH = os.path.join(BASE_DIR, 'video_point_love')

#永中云在线文档转换
IP_KEY = '340299661'

#缓存配置
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 1
}

#social_django的apikey配置
SOCIAL_AUTH_WEIBO_KEY = '3870099249'
SOCIAL_AUTH_WEIBO_SECRET = '664c305aa0e7cc75728070f72e27b8fa'

SOCIAL_AUTH_QQ_KEY = '1106800343'
SOCIAL_AUTH_QQ_SECRET = 'B69uwrXEq4gtrxYo'

#登录成功后的跳转页http://python-social-auth.readthedocs.io/en/latest/configuration/settings.html
# SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://118.24.116.137:8001'
# SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://172.19.73.62:4864/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/test_weibo/'